version: '3.7'

services:
  app:
    image: node:lts
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - nginx-proxy
    hostname: dev-stockinfo-front
    command: tail -f /dev/null

networks:
  nginx-proxy:
    external: true
